import React, { useState } from "react";
import { FaPlus, FaMinus } from "react-icons/fa6";

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleDropdown = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const faqs = [
    {
      question: "Is the content unique?",
      answer:
        "95% of the content generated by the AI is unique and original. We also provide a uniqueness score for longer form content generated so you can have peace of mind to know that the content you have received is unique.",
    },
    {
      question: "How is the content generated?",
      answer:
        "We make use of a variety of AI models, with Generative Pre-trained Transformer 3 is an autoregressive language model which uses deep learning to produce human-like text. It's a game changer for content creators.",
    },
    {
      question: "Who retains the copyright?",
      answer: "You do. We will not claim copyright over content generated by the AI for you.",
    },
    {
      question: "What languages do you support?",
      answer: "We currently support all languages supported by Google Translate.",
    },
    {
      question: "Is there discount for non-profits?",
      answer: "Please get in touch with us below.",
    },
  ];

  return (
    <main className="bg-[#0F062C] md:px-16">
      <div className="xl:px-16 md:px-6 px-0 pb-10 w-full container faqs" id="faqs">
        <div className="py-10">
          <h2 className="lg:text-6xl text-4xl font-normal relative lg:p-10 md:p-6 p-4">
            <span className="border-text text-white opacity-50 absolute md:top-3 lg:top-4 top-0 lg:left-10">
              FREQUENTLY ASKED
            </span>
            <span className="gradient-span-1 text-[#EC5CFF] relative lg:p-6 p-6 font-[600]">
              QUESTIONS
            </span>
          </h2>
          <p className="text-center w-full !text-white pt-6 md:pt-0 text-base md:text-[21px] font-[400]">
            We're dedicated to assisting individuals interested in generating AI-driven content and images.
          </p>
        </div>
        <div className="w-full flex items-center justify-center lg:px-10 md:px-6 px-4">
          <div className="flex flex-col items-center">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="w-full my-1 overflow-hidden rounded-md border border-[#FFFFFF14] hover:bg-white/10 bg-white/5 transition duration-500"
              >
                <div
                  className="rounded-sm w-full p-6 py-4 cursor-pointer transition-all duration-300 ease-in-out"
                  onClick={() => toggleDropdown(index)}
                >
                  <div className="flex items-center w-full justify-between">
                    <span className="sm:text-base font-medium md:text-xl text-lg text-white">
                      {faq.question}
                    </span>
                    <div className="text-white flex items-center">
                      {openIndex === index ? <FaMinus size={20} /> : <FaPlus size={20} />}
                    </div>
                  </div>
                </div>
                <div
                  className={`px-8 drop-shadow-lg transition-all duration-300 ease-in-out ${
                    openIndex === index ? "max-h-40 py-4" : "max-h-0"
                  } overflow-hidden`}
                >
                  <p className="text-white border-t border-t-white/30 font-light md:text-xl text-lg mt-2">
                    {faq.answer}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  );
};

export default FAQ;
